name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install
      working-directory: my-react-app

    - name: Build the Project
      run: npm run build
      working-directory: my-react-app

    - name: Deploy to Hostinger via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        script: |
          rm -rf ~/domains/bisque-porcupine-621798.hostingersite.com/public_html/*
          cp -r ~/my-react-app/build/* ~/domains/bisque-porcupine-621798.hostingersite.com/public_html/
